### ISSUE TITLE
Issue dns error pada server SIPM

### ISSUE THREAD

**Issue by lutfiihsan** [setditjen-psdkp/.github#4]
### ISSUE
- server tidak bisa konek ke internet
- server tidak bisa integrasi ke github
- dns nya perlu diupdate
##result
![Image](https://github.com/setditjen-psdkp/.github/assets/36567675/e17099f1-78d8-490b-938c-98b767d2e432)

### SOLUTION
- edit dns pada lokasi _nano /etc/resolv.conf_
- dns diganti dengan alamat baru : _192.168.12.134_ dan _192.168.12.54_
##before
![Image](https://github.com/setditjen-psdkp/.github/assets/36567675/d89609a4-a80b-4f81-a615-609f58fb61c6)

##after
![Image](https://github.com/setditjen-psdkp/.github/assets/36567675/670d912c-93b3-4f02-8c87-b2c874b10ad0)

##result
![Image](https://github.com/setditjen-psdkp/.github/assets/36567675/5d222a93-58ad-480a-88e8-49014a898e7c)

![Image](https://github.com/setditjen-psdkp/.github/assets/36567675/b892346c-a20c-4eac-85c7-41b1f1e6953b)

**Comment by lutfiihsan** [comment]
update: simpan setingan dns permanent

```
/etc/NetworkManager/NetworkManager.conf

[main]
dns=none
#plugins=ifcfg-rh,ibft
```

**Comment by lutfiihsan** [comment]
info @rizkhal

**Comment by rizkhal** [comment]
LGTM!

Thanks for sharing mas 🙌

**Comment by lutfiihsan** [comment]
> LGTM!
> 
> Thanks for sharing mas 🙌

dapet gelar gk gue khal?

**Comment by rizkhal** [comment]
> > LGTM!
> > Thanks for sharing mas 🙌
> 
> dapet gelar gk gue khal?

dapet mas, "the best dns manager ever and ever and ever again" 🤣
